
variable "ami_id" {
  type    = string
  default = "ami-6f68cf0f"
}

variable "app_name" {
  type    = string
  default = "httpd"
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "PACKER-DEMO-${var.app_name}"
  instance_type = "t2.micro"
  region        = "eu-west-1"
  source_ami    = "${var.ami_id}"
  ssh_username  = "ec2-user"
  tags = {
    Env  = "DEMO"
    Name = "PACKER-DEMO-${var.app_name}"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    script = "demo-script.sh"
  }
}
